#include "qcc/keyword.h"

const Keyword* kwrd_map[KWRD_END] = {
  &(Keyword) { .kind = KWRD_SWITCH, .str = "switch"},
  &(Keyword) { .kind = KWRD_CASE, .str = "case" },
  &(Keyword) { .kind = KWRD_DEFAULT, .str = "default" },
  &(Keyword) { .kind = KWRD_IF, .str = "if" },
  &(Keyword) { .kind = KWRD_ELSE, .str = "else" },
  &(Keyword) { .kind = KWRD_FOR, .str = "for" },
  &(Keyword) { .kind = KWRD_WHILE, .str = "while" },
  &(Keyword) { .kind = KWRD_DO, .str = "do" },
  &(Keyword) { .kind = KWRD_CONTINUE, .str = "continue" },
  &(Keyword) { .kind = KWRD_GOTO, .str = "goto" },
  &(Keyword) { .kind = KWRD_BREAK, .str = "break" },
  &(Keyword) { .kind = KWRD_RETURN, .str = "return" },
  &(Keyword) { .kind = KWRD_TYPEDEF, .str = "typedef" },
  &(Keyword) { .kind = KWRD_EXTERN, .str = "extern" },
  &(Keyword) { .kind = KWRD_STATIC, .str = "static" },
  &(Keyword) { .kind = KWRD_AUTO, .str = "auto" },
  &(Keyword) { .kind = KWRD_REGISTER, .str = "register" },
  &(Keyword) { .kind = KWRD_VOID, .str = "void" },
  &(Keyword) { .kind = KWRD_CHAR, .str = "char" },
  &(Keyword) { .kind = KWRD_SHORT, .str = "short" },
  &(Keyword) { .kind = KWRD_INT, .str = "int" },
  &(Keyword) { .kind = KWRD_LONG, .str = "long" },
  &(Keyword) { .kind = KWRD_FLOAT, .str = "float" },
  &(Keyword) { .kind = KWRD_DOUBLE, .str = "double" },
  &(Keyword) { .kind = KWRD_SIGNED, .str = "signed" },
  &(Keyword) { .kind = KWRD_UNSIGNED, .str = "unsigned" },
  &(Keyword) { .kind = KWRD_BOOL, .str = "_Bool" },
  &(Keyword) { .kind = KWRD_COMPLEX, .str = "_Complex" },
  &(Keyword) { .kind = KWRD_IMAGINARY, .str = "_Imaginary" },
  &(Keyword) { .kind = KWRD_CONST, .str = "const" },
  &(Keyword) { .kind = KWRD_RESTRICT, .str = "restrict" },
  &(Keyword) { .kind = KWRD_VOLATILE, .str = "volatile" },
  &(Keyword) { .kind = KWRD_STRUCT, .str = "struct" },
  &(Keyword) { .kind = KWRD_UNION, .str = "union" },
  &(Keyword) { .kind = KWRD_ENUM, .str = "enum" },
  &(Keyword) { .kind = KWRD_INLINE, .str = "inline" },
};

